/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db_pharmacymanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author tasfi
 */
public class Login extends javax.swing.JFrame {
    
    String role = "Manager";

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        userName_Label = new javax.swing.JLabel();
        pw_Label = new javax.swing.JLabel();
        signIn_Button = new javax.swing.JButton();
        reset_Button = new javax.swing.JButton();
        signIn_Label = new javax.swing.JLabel();
        pw_PasswordField = new javax.swing.JPasswordField();
        userName_TextField = new javax.swing.JTextField();
        Role_Label = new javax.swing.JLabel();
        role_jComboBox1 = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pharmacy Management System");

        jPanel3.setBackground(new java.awt.Color(97, 212, 195));
        jPanel3.setPreferredSize(new java.awt.Dimension(840, 550));

        jPanel5.setBackground(new java.awt.Color(36, 47, 65));
        jPanel5.setPreferredSize(new java.awt.Dimension(420, 550));

        userName_Label.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        userName_Label.setForeground(new java.awt.Color(204, 204, 204));
        userName_Label.setText("USER NAME");

        pw_Label.setBackground(new java.awt.Color(204, 204, 204));
        pw_Label.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pw_Label.setForeground(new java.awt.Color(204, 204, 204));
        pw_Label.setText("PASSWORD");

        signIn_Button.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        signIn_Button.setForeground(new java.awt.Color(255, 255, 255));
        signIn_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/db_pharmacymanagement/back.png"))); // NOI18N
        signIn_Button.setText("Sign In");
        signIn_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signIn_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signIn_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signIn_ButtonActionPerformed(evt);
            }
        });

        reset_Button.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        reset_Button.setForeground(new java.awt.Color(255, 255, 255));
        reset_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/db_pharmacymanagement/back.png"))); // NOI18N
        reset_Button.setText("Reset");
        reset_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reset_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_ButtonActionPerformed(evt);
            }
        });

        signIn_Label.setBackground(new java.awt.Color(204, 204, 204));
        signIn_Label.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        signIn_Label.setForeground(new java.awt.Color(204, 204, 204));
        signIn_Label.setText("SIGN IN");

        pw_PasswordField.setBackground(new java.awt.Color(36, 47, 65));
        pw_PasswordField.setForeground(new java.awt.Color(255, 255, 255));
        pw_PasswordField.setText("jPasswordField1");
        pw_PasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pw_PasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pw_PasswordFieldFocusGained(evt);
            }
        });
        pw_PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw_PasswordFieldActionPerformed(evt);
            }
        });

        userName_TextField.setBackground(new java.awt.Color(36, 47, 65));
        userName_TextField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        userName_TextField.setForeground(new java.awt.Color(255, 255, 255));
        userName_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        userName_TextField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        userName_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userName_TextFieldMouseClicked(evt);
            }
        });
        userName_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userName_TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pw_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pw_Label)
                            .addComponent(signIn_Label)
                            .addComponent(userName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userName_Label)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reset_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(signIn_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(signIn_Label)
                .addGap(32, 32, 32)
                .addComponent(userName_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(pw_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pw_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(signIn_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reset_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        Role_Label.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Role_Label.setForeground(new java.awt.Color(255, 255, 255));
        Role_Label.setText("Select your role ");

        role_jComboBox1.setBackground(new java.awt.Color(97, 212, 195));
        role_jComboBox1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        role_jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Salesman" }));
        role_jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                role_jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Role_Label)
                    .addComponent(role_jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(Role_Label)
                .addGap(31, 31, 31)
                .addComponent(role_jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pw_PasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pw_PasswordFieldFocusGained
        // TODO add your handling code here:
        pw_PasswordField.setText("");
    }//GEN-LAST:event_pw_PasswordFieldFocusGained

    private void userName_TextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userName_TextFieldMouseClicked
        // TODO add your handling code here:
        userName_TextField.setText("");
    }//GEN-LAST:event_userName_TextFieldMouseClicked

    private void userName_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userName_TextFieldActionPerformed
        // TODO add your handling code here:
        
        userName_TextField.setText("");
        pw_PasswordField.setText("");
    }//GEN-LAST:event_userName_TextFieldActionPerformed

    private void reset_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_ButtonActionPerformed
        // TODO add your handling code here:
        userName_TextField.setText("");
        pw_PasswordField.setText("");
    }//GEN-LAST:event_reset_ButtonActionPerformed

    private void signIn_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signIn_ButtonActionPerformed
        // TODO add your handling code here:
        
         try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=PMS;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            String sql = "Select Uid from SystemUser where UserName= ? and userPassword = ? and Role = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, userName_TextField.getText());
            pst.setString(2, pw_PasswordField.getText());
            pst.setString(3, role);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
               //setVisible(false);
               String UserID = rs.getString(ICONIFIED);
               // Transfer which dashboard is suitable according to role 
               if(role == "Manager"){
                    JOptionPane.showMessageDialog(null, "Welcome To Pharmacy Management System");
                    Succes field= new Succes();
                    field.setVisible(true);
                   
                   System.out.println("execute as manager");
                    Dashboard dashBoard = new Dashboard(UserID);
                    dashBoard.UserInfo(UserID,userName_TextField.getText(), role);
                    userName_TextField.setText("");
                    pw_PasswordField.setText("");
                    setVisible(false);
                    dashBoard.setVisible(true);
               }
               else{
                    JOptionPane.showMessageDialog(null, "Welcome To Pharmacy Management System");
                    Succes field= new Succes();
                    field.setVisible(true);
                   
                    DashboardSalesman dashsales = new DashboardSalesman(UserID);
                    dashsales.UserInfo(userName_TextField.getText(), role);
                    userName_TextField.setText("");
                    pw_PasswordField.setText("");
                    setVisible(false);
                    dashsales.setVisible(true);
               }
                
               
            }
            else{
                JOptionPane.showMessageDialog(null, "Username or Password or Role not Correct");
                userName_TextField.setText("");
                pw_PasswordField.setText("");
            }
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
        
    }//GEN-LAST:event_signIn_ButtonActionPerformed

    private void role_jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_role_jComboBox1ActionPerformed
        // TODO add your handling code here:
        role = role_jComboBox1.getSelectedItem().toString();
    }//GEN-LAST:event_role_jComboBox1ActionPerformed

    private void pw_PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw_PasswordFieldActionPerformed
        // TODO add your handling code here:
        pw_PasswordField.setText("");
    }//GEN-LAST:event_pw_PasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
     private static class Succes {

        public Succes() {
        }

        private void setVisible(boolean b) {
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Role_Label;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel pw_Label;
    private javax.swing.JPasswordField pw_PasswordField;
    private javax.swing.JButton reset_Button;
    private javax.swing.JComboBox<String> role_jComboBox1;
    private javax.swing.JButton signIn_Button;
    private javax.swing.JLabel signIn_Label;
    private javax.swing.JLabel userName_Label;
    private javax.swing.JTextField userName_TextField;
    // End of variables declaration//GEN-END:variables
}
