/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db_pharmacymanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author tasfi
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        register_Button = new javax.swing.JButton();
        delete_Button = new javax.swing.JButton();
        updatePW_Button = new javax.swing.JButton();
        phone_TextField = new javax.swing.JTextField();
        address_TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        role = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        username_update_TextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        confirmPW_PasswordField = new javax.swing.JPasswordField();
        PW_PasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(97, 212, 195));
        jPanel3.setPreferredSize(new java.awt.Dimension(840, 550));

        jPanel5.setBackground(new java.awt.Color(36, 47, 65));
        jPanel5.setPreferredSize(new java.awt.Dimension(420, 550));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("ADDRESS");

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("PHONE NUMBER");

        register_Button.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        register_Button.setForeground(new java.awt.Color(255, 255, 255));
        register_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/db_pharmacymanagement/back_button.png"))); // NOI18N
        register_Button.setText("Register");
        register_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        register_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_ButtonActionPerformed(evt);
            }
        });

        delete_Button.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        delete_Button.setForeground(new java.awt.Color(255, 255, 255));
        delete_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/db_pharmacymanagement/back_button.png"))); // NOI18N
        delete_Button.setText("Delete");
        delete_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_ButtonActionPerformed(evt);
            }
        });

        updatePW_Button.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        updatePW_Button.setForeground(new java.awt.Color(255, 255, 255));
        updatePW_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/db_pharmacymanagement/back.png"))); // NOI18N
        updatePW_Button.setText("Update Password");
        updatePW_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updatePW_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePW_ButtonActionPerformed(evt);
            }
        });

        phone_TextField.setBackground(new java.awt.Color(36, 47, 65));
        phone_TextField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        phone_TextField.setForeground(new java.awt.Color(255, 255, 255));
        phone_TextField.setText("Enter your phone number");
        phone_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        phone_TextField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        phone_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phone_TextFieldMouseClicked(evt);
            }
        });
        phone_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_TextFieldActionPerformed(evt);
            }
        });

        address_TextField.setBackground(new java.awt.Color(36, 47, 65));
        address_TextField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        address_TextField.setForeground(new java.awt.Color(255, 255, 255));
        address_TextField.setText("Enter you address");
        address_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        address_TextField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        address_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                address_TextFieldMouseClicked(evt);
            }
        });
        address_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_TextFieldActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("ROLE");

        role.setBackground(new java.awt.Color(36, 47, 65));
        role.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        role.setForeground(new java.awt.Color(255, 255, 255));
        role.setText("Enter your Role");
        role.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        role.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        role.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roleMouseClicked(evt);
            }
        });
        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(phone_TextField)
                    .addComponent(role)
                    .addComponent(updatePW_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(address_TextField)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(register_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delete_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(address_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phone_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updatePW_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("USER NAME");

        username_update_TextField.setBackground(new java.awt.Color(97, 212, 195));
        username_update_TextField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        username_update_TextField.setForeground(new java.awt.Color(255, 255, 255));
        username_update_TextField.setText("Enter you username");
        username_update_TextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        username_update_TextField.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        username_update_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                username_update_TextFieldMouseClicked(evt);
            }
        });
        username_update_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_update_TextFieldActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PASSWORD");

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CONFIRM PASSWORD");

        confirmPW_PasswordField.setBackground(new java.awt.Color(97, 212, 195));
        confirmPW_PasswordField.setForeground(new java.awt.Color(255, 255, 255));
        confirmPW_PasswordField.setText("jPasswordField1");
        confirmPW_PasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        confirmPW_PasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPW_PasswordFieldFocusGained(evt);
            }
        });

        PW_PasswordField.setBackground(new java.awt.Color(97, 212, 195));
        PW_PasswordField.setForeground(new java.awt.Color(255, 255, 255));
        PW_PasswordField.setText("jPasswordField1");
        PW_PasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        PW_PasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PW_PasswordFieldFocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIGN UP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(username_update_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addComponent(confirmPW_PasswordField))
                    .addComponent(PW_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_update_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PW_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPW_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatePW_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePW_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatePW_ButtonActionPerformed

    private void phone_TextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phone_TextFieldMouseClicked
        // TODO add your handling code here:
        phone_TextField.setText("");
    }//GEN-LAST:event_phone_TextFieldMouseClicked

    private void phone_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_TextFieldActionPerformed

    private void username_update_TextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_username_update_TextFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_username_update_TextFieldMouseClicked

    private void username_update_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_update_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_update_TextFieldActionPerformed

    private void address_TextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_address_TextFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_address_TextFieldMouseClicked

    private void address_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_TextFieldActionPerformed

    private void confirmPW_PasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPW_PasswordFieldFocusGained
        // TODO add your handling code here:
        confirmPW_PasswordField.setText("");
    }//GEN-LAST:event_confirmPW_PasswordFieldFocusGained

    private void PW_PasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PW_PasswordFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PW_PasswordFieldFocusGained

    private void register_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_ButtonActionPerformed
        // TODO add your handling code here:
        
         try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=PMS;user=sa;password=123456";
            Connection con = DriverManager.getConnection(url);
            String sql = "Insert into Login"
                    +"(UserName,UserPassword,UserRole)"
                    +"values(?,?,?)";
            
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, username_update_TextField.getText());
            pst.setString(2, PW_PasswordField.getText());
            pst.setString(3, role.getText());
           // ResultSet rs = 
            pst.executeUpdate();
        
               JOptionPane.showMessageDialog(null, "Successfully Registered");
               SignUp.Succes field= new  SignUp.Succes();
               field.setVisible(true);
               //setVisible(false);
                username_update_TextField.setText("");
                PW_PasswordField.setText("");
               
       
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_register_ButtonActionPerformed

    private void roleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roleMouseClicked

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleActionPerformed

    private void delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }
    
     private static class Succes {

        public Succes() {
        }

        private void setVisible(boolean b) {
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PW_PasswordField;
    private javax.swing.JTextField address_TextField;
    private javax.swing.JPasswordField confirmPW_PasswordField;
    private javax.swing.JButton delete_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField phone_TextField;
    private javax.swing.JButton register_Button;
    private javax.swing.JTextField role;
    private javax.swing.JButton updatePW_Button;
    private javax.swing.JTextField username_update_TextField;
    // End of variables declaration//GEN-END:variables
}
